<div class="page-header">
    <h1>Suas <strong>despesas</strong> e <strong>receitas</strong> fixas <small>(<?=$this->total ?>)</small></h1>
</div>
<div class="panel panel-default">

    <div class="panel-heading" style="position: relative">
        <span class="panel-title">Suas despesas ou receitas que são fixas todos os meses:</span>
        <a href="<?=$this->url('fixos', 'create', array(), true) ?>" class="btn btn-xs btn-success" style="position: absolute; top: 50%; right: 15px; margin-top: -11px;">
            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
            <span class="visible-lg-inline visible-md-inline">Adicionar</span>
        </a>
    </div>
    <?php if($this->total > 0) : ?>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="50%">Descrição</th>
                    <th width="30%">Valor</th>
                    <th width="15%">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data as $item) : ?>
                    <tr>
                        <td><?=$item->getId() ?></td>
                        <td><?=$item->getDescricao() ?></td>
                        <td style="color: <?=$item->getValor() >= 0 ? '#449d44' : '#d43f3a' ?>">
                            <span class="glyphicon glyphicon-<?=$item->getValor() >= 0 ? 'plus' : 'minus' ?>-sign" aria-hidden="true"></span>
                            R$
                            <?=number_format(abs($item->getValor()), 2, ',', '.') ?>
                        </td>
                        <td>
                            <a href="<?=$this->url('fixos', 'update', array('fixo_id' => $item->getId()), true) ?>" class="btn btn-xs btn-primary" title="Editar">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                <span class="visible-lg-inline">Editar</span>
                            </a>
                            <a href="<?=$this->url('fixos', 'delete', array('fixo_id' => $item->getId()), true) ?>" class="btn btn-xs btn-danger" title="Remover">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                <span class="visible-lg-inline">Remover</span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="panel-body" style="text-align: center;">
            <h4>Nenhuma <strong>despesas</strong> ou <strong>receitas</strong> registrada.</h4>
        </div>
    <?php endif ?>
</div>
