<?php
/**
 * @TODO: Arrumar o layout
 */
?>

<div class="page-header">
  <h1>Controle de despesas</h1>
</div>

<div class="col-xs-12 col-sm-6">
    <div class="panel panel-default">
        <div class="panel-body">
            <h3>Já é cadastrado?</h3>
            <hr>
            <form method="post" action="<?=$this->url('site', 'login', array(), true) ?>">
                <div class="form-group">
                    <label for="user-login">Login</label>
                    <input type="text" class="form-control" id="user-login" name="user-login" >
                </div>
                <div class="form-group">
                    <label for="user-passwd">Senha</label>
                    <input type="password" class="form-control" id="user-passwd" name="user-passwd" >
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block" value="Entrar">
                </div>
            </form>
        </div>
    </div>
</div>

<div class="col-xs-12 col-sm-6">
    <div class="panel panel-default">
        <div class="panel-body">
            <h3>Realize seu cadastro agora</h3>
            <hr>
            <form method="post" action="<?=$this->url('site', 'singup', array(), true) ?>" >
                <div class="form-group">
                    <label for="singup-name">Nome</label>
                    <input type="text" class="form-control" id="singup-name" name="singup-name">
                </div>
                <div class="form-group">
                    <label for="singup-lastname">Sobrenome</label>
                    <input type="text" class="form-control" id="singup-lastname" name="singup-lastname">
                </div>
                <div class="form-group">
                    <label for="singup-login">Login</label>
                    <input type="text" class="form-control" id="singup-login" name="singup-login" >
                </div>
                <div class="form-group">
                    <label for="singup-passwd">Senha</label>
                    <input type="password" class="form-control" id="singup-passwd" name="singup-passwd" >
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-success btn-block" value="Cadastrar" name="singup-submit">
                </div>
            </form>
        </div>
    </div>
</div>
