<?php
/**
 * @TODO: Arrumar o layout
 */
?>

<div class="page-header">
  <h1>Criar usuário</h1>
</div>
<?php if(!$this->error && isset($this->messages['success'])): ?>
    <div class="alert alert-success" role="alert">
        <?=$this->messages['success'] ?>
    </div>
<?php else: ?>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="post">

                    <div class="form-group <?=isset($this->messages['singup-name']) ? 'has-error' : '' ?>">
                        <label for="singup-name">Nome</label>
                        <input type="text" class="form-control" id="singup-name" name="singup-name" value="<?= $this->data !== null ? $this->data->getNome() : '' ?>" >
                        <?php if(isset($this->messages['singup-name'])): ?>
                            <span class="help-block" ><?=$this->messages['singup-name'] ?></span>
                        <?php endif ?>
                    </div>

                    <div class="form-group <?=isset($this->messages['singup-lastname']) ? 'has-error' : '' ?>">
                        <label for="singup-lastname">Sobrenome</label>
                        <input type="text" class="form-control" id="singup-lastname" name="singup-lastname" value="<?= $this->data !== null ? $this->data->getSobrenome() : '' ?>">
                        <?php if(isset($this->messages['singup-lastname'])): ?>
                            <span class="help-block" ><?=$this->messages['singup-lastname'] ?></span>
                        <?php endif ?>
                    </div>

                    <div class="form-group <?=isset($this->messages['singup-login']) ? 'has-error' : '' ?>">
                        <label for="singup-login">Login</label>
                        <input type="text" class="form-control" id="singup-login" name="singup-login" value="<?= $this->data !== null ? $this->data->getLogin() : '' ?>" >
                        <?php if(isset($this->messages['singup-login'])): ?>
                            <span class="help-block" ><?=$this->messages['singup-login'] ?></span>
                        <?php endif ?>
                    </div>

                    <div class="form-group <?=isset($this->messages['singup-passwd']) ? 'has-error' : '' ?>">
                        <label for="singup-passwd">Senha</label>
                        <input type="password" class="form-control" id="singup-passwd" name="singup-passwd" >
                        <?php if(isset($this->messages['singup-passwd'])): ?>
                            <span class="help-block" ><?=$this->messages['singup-passwd'] ?></span>
                        <?php endif ?>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-block" value="Cadastrar" name="singup-submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php endif ?>

<div class="col-xs-12" style="text-align: center; margin-bottom: 30px;">
    <a href="<?=$this->url('site', 'index', array(), true) ?>">Ir para o ínicio</a>
</div>
