<?php
$renderer = '';
$receitas = 0;
$despesas = 0;
if($this->mes !== null){

    $month = (int) $this->mes->getMes()->format('m');
    $year = (int) $this->mes->getMes()->format('Y');

    switch ($month) {
        case 1: $renderer = 'Janeiro'; break;
        case 2: $renderer = 'Fevereiro'; break;
        case 3: $renderer = 'Março'; break;
        case 4: $renderer = 'Abril'; break;
        case 5: $renderer = 'Maio'; break;
        case 6: $renderer = 'Junho'; break;
        case 7: $renderer = 'Julho'; break;
        case 8: $renderer = 'Agosto'; break;
        case 9: $renderer = 'Setembro'; break;
        case 10: $renderer = 'Outubro'; break;
        case 11: $renderer = 'Novembro'; break;
        case 12: $renderer = 'Dezembro'; break;
    }

    $renderer .= '/'.$year;
}
?>
<div class="page-header">
    <h1>Suas <strong>despesas</strong> e <strong>receitas</strong> por mês <small>(<?=$this->totalData ?>)</small></h1>
</div>
<div class="panel panel-default">

    <div class="panel-heading" style="position: relative">
        <span class="panel-title">Suas despesas ou receitas que de <strong><?=$renderer ?></strong>:</span>
        <a href="<?=$this->url('mes', 'create', array(), true) ?>" class="btn btn-xs btn-success" style="position: absolute; top: 50%; right: 15px; margin-top: -11px;">
            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
            <span class="visible-lg-inline visible-md-inline">Adicionar</span>
        </a>
    </div>
    <?php if($this->totalData > 0) : ?>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="50%">Descrição</th>
                    <th width="30%">Valor</th>
                    <th width="15%">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data as $item) : ?>
                    <?php

                    if($item->getValor() >= 0):
                        $receitas += $item->getValor();
                    else:
                        $despesas += $item->getValor();
                    endif;
                    ?>
                    <tr>
                        <td><?=$item->getId() ?></td>
                        <td><?=$item->getDescricao() ?></td>
                        <td style="color: <?=$item->getValor() >= 0 ? '#449d44' : '#d43f3a' ?>">
                            <span class="glyphicon glyphicon-<?=$item->getValor() >= 0 ? 'plus' : 'minus' ?>-sign" aria-hidden="true"></span>
                            R$
                            <?=number_format(abs($item->getValor()), 2, ',', '.') ?>
                        </td>
                        <td>
                            <a href="<?=$this->url('mes', 'update', array('financa_mes_id' => $item->getId()), true) ?>" class="btn btn-xs btn-primary" title="Editar">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                <span class="visible-lg-inline">Editar</span>
                            </a>
                            <a href="<?=$this->url('mes', 'delete', array('financa_mes_id' => $item->getId()), true) ?>" class="btn btn-xs btn-danger" title="Remover">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                <span class="visible-lg-inline">Remover</span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php $total = $receitas + $despesas; ?>
        <div class="panel-footer" style="text-align: center;">
            <div class="container-fluid">
                <div class="col-xs-4" style="color: #449d44">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    Receitas:
                    <?=number_format(abs($receitas), 2, ',', '.')  ?>
                </div>
                <div class="col-xs-4" style="color: #d43f3a">
                    <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                    Despesas:
                    <?=number_format(abs($despesas), 2, ',', '.')  ?>
                </div>
                <div class="col-xs-4" style="color: <?=$total >= 0 ? '#449d44' : '#d43f3a' ?>">
                    <span class="glyphicon glyphicon-<?=$total >= 0 ? 'plus' : 'minus' ?>-sign" aria-hidden="true"></span>
                    Total:
                    <?=number_format(abs($total), 2, ',', '.')  ?>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="panel-body" style="text-align: center;">
            <h4>Nenhuma <strong>despesas</strong> ou <strong>receitas</strong> registrada.</h4>
        </div>
    <?php endif ?>
</div>
